### ISSUE TITLE
website backend login weirdness

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/manifold#826]
Reported issue:

- user without manifold backend access attempts to login (https://library.temple.edu/admin) ; during this process, screen flashes for a second that shows login as some other user, then redirects them to manifold homepage with pop-up saying 'user not permitted' (or whatever the desired message is)
- if in same browser / session with a different user then trying to login to hte manifold backend (https://library.temple.edu/admin), the page doesn't allow login, just shows 'not permitted' error.

Need to replicate for myself. First impressions is the second step issue is due to session stickiness at the LB level. First problem... google oauth response slowness? avoiding further guessing until can replicate / investigate.

**Comment by nomadicoder** [comment]
Issue no longer relevant.
